config/routes.rb
Rails.application.routes.draw do
  get 'wall/index'
  post 'wall/create'
  post 'wall/like/:post_id', to: 'wall#like', as: 'like'
  post 'wall/unlike/:post_id', to: 'wall#unlike', as: 'unlike'

  get 'profile/:name', to: 'users#index', as: 'profile'
  get 'signup', to: 'users#new'
  post 'users' => 'users#create'

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  root 'wall#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :message
end

app/models/message.rb
class Message < ApplicationRecord
  validates :message, presence: true, length: { maximum: 140 }

  belongs_to :author, :class_name => "User", foreign_key: "user_id"
  has_many :likes
  has_many :users, :through => :likes
end

app/models/user.rb
# https://gist.github.com/iscott/4618dc0c85acb3daa5c26641d8be8d0d

class User < ApplicationRecord

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i

  validates :username, presence: true, length: {maximum: 50}
  validates :email, presence: true, length: {maximum: 255},
                    format: {with: VALID_EMAIL_REGEX}

  validates :password, presence: true,
                       length: { minimum: 6 }
  validates :password_confirmation, presence: true,
                                    length: { minimum: 6 }

  has_secure_password

  has_many :messages, dependent: :destroy

  has_many :likes
  has_many :messages, through: :likes
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :current_user
  helper_method :is_liked

  def is_liked(post)
    if post.nil? || current_user.nil?
      return false
    else
      like = Like.find_by user_id: current_user.id, message_id: post.id
      unless like.nil?
        return true
      end
    end
    return false
  end

  def current_user
    # this-> ||= is something with memoization
    # its used to not hit database everytime we want to access current_user
    # a ||= b (double pipe equals OR or-equals) sets a with b, if a is falsey or undefined
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def authorize
    if current_user.nil?
      redirect_to login_path, alert: "You must be logged in to access this page."
      return false
    end
    return true
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def new
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
  
  def create
    user = User.find_by_username(params[:login][:username])
    if user && user.authenticate(params[:login][:password])
      session[:user_id] = user.id.to_s
      redirect_to root_path, notice: "Logged in"
    else
      flash.alert = "Wrong username or password"
      render :new
    end
  end

  def destroy
      session.delete(:user_id)
      redirect_to login_path, notice: "Logged out"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    u = User.find_by_username(params[:name])
    unless u.nil?
      @user = u
    else
      render :error
    end
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    @user.email.downcase!

    if @user.save
      flash.notice = "Added user"
      redirect_to root_path
    else
      flash.alert = @user.errors.messages.to_s
      render :new
    end
  end

  def user_params
    params.require(:user).permit(:username, :email, :password, :password_confirmation)
  end

end

app/controllers/wall_controller.rb
class WallController < ApplicationController
  def index
    @messages = Message.all
  end

  def create
    authorize or return
    @message = Message.create(author: current_user, message: params[:message][:message])
    redirect_to wall_index_path
  end

  def like
    authorize or return
    m = Message.find_by_id(params[:post_id])
    unless m.nil?
      Like.create message_id: params[:post_id], user_id: current_user.id
    end
    redirect_to wall_index_path
  end

  def unlike
    authorize or return
    m = Message.find_by_id(params[:post_id])
    unless m.nil?
      l = Like.find_by message_id: params[:post_id], user_id: current_user.id
      unless l.nil?
        l.destroy
      end
    end
    redirect_to wall_index_path
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/wall_helper.rb
module WallHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.haml
%html
  %head
    = csrf_meta_tags
    = csp_meta_tag

    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'

  %body{:class => ["site_background"]}
    %div{:class => ["login_panel"]}
      - if current_user
        = "Logged in as "
        = link_to current_user.username, profile_path(name: current_user.username), class: "link_style"
        = link_to "Log out", logout_path, method: :delete
      - else
        = link_to "Sign up", signup_path 
        |
        = link_to "Log in", login_path

    %div
      - if flash.notice
        %div{:style => "color:green"}
          = flash.notice

      - if flash.alert
        %div{:style => "color:red"}
          = flash.alert
      
    = yield

app/views/users/error.haml
%title User Error

%div{:class => "user_not_found"}
  User with such name doesn't exist

app/views/users/index.haml
%title User profile
%div{:class => "profile-page"}

  %div{:class => "profile-details"}
    %br
    = "#{@user.username}"
    %br
    = "#{@user.email}"
    %br
    = "Joined: #{@user.created_at}"

  %div{:class => "profile-tweets"}
    Tweets:
    %br
    - @user.messages.each do |m|
      %div{:class => ["tweet"]}
        %div{:class => "message_header"}
          %span{:id => "username"}
            = link_to m.author.username, profile_path(name: m.author.username)
          %span{:id => "time_string"}
            *
            = m.created_at.strftime "%b %-d"
        %div{:class => ["message_body"]}
          = m.message
        %div{:class => ["message_footer"]}
          Likes: 0 | Replies: 0

app/views/users/new.haml
%div{:class => 'login_form'}
  %h1 Sign up

  = form_for @user do |f|
    %div
      = f.label :username
      = f.text_field :username, autofocus: true

    %div
      = f.label :email
      = f.text_field :email

    %div
      = f.label :password
      = f.password_field :password

    %div
      = f.label :password_confirmation
      = f.password_field :password_confirmation

    %div
      = f.submit "Sign up!"

app/views/wall/index.haml
%title Your wall

%div{:class => ["wall"]}
  %p
    Say something!
    = form_for :message, url: {action: "create"}  do |f|
      = f.text_field :message
      = f.submit

  %br
  %p
    - @messages.each do |m|
      %div{:class => ["tweet"]}
        %div{:class => "message_header"}
          %span{:id => "username"}
            = link_to m.author.username, profile_path(name: m.author.username), class: "link_style"
          %span{:id => "time_string"}
            *
            = m.created_at.strftime "%b %-d"
        %div{:class => ["message_body"]}
          = m.message
        %div{:class => ["message_footer"]}
          %div{:id => "reactions"}
            - if is_liked(m)
              = link_to "❤️You Like It!", unlike_path(post_id: m.id), class: "link_style", method: :post
            - else
              = link_to "❤️Like", like_path(post_id: m.id), class: "link_style", method: :post
          Likes:
          = m.likes.count
          | Replies: 0